name: jappeos_desktop
description: Desktop environment for JappeOS.
publish_to: 'none'
version: 1.0.0+1
google_sign_in_web: ^0.9.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO
  shadcn_flutter:
    git:
      url: https://github.com/JappeOS/shadcn_flutter.git
      ref: master

  #jdwm_flutter:
  #  git:
  #    url: https://github.com/JappeOS/JDWM.git
  #    ref: main
  #    path: jdwm_flutter

  jdwm:
    path: vendor/jdwm

  jappeos_desktop_base:
    git:
      url: https://github.com/JappeOS/jappeos_desktop_base.git
      ref: main

  jappeos_services:
    git:
      url: https://github.com/JappeOS/jappeos_services.git
      ref: dev
  #jappeos_services:
  #  path: ../jappeos_services

  provider: ^6.0.3
  event: ^3.1.0
  highlight: ^0.7.0
  flutter_svg: ^2.0.6
  vector_math: ^2.1.4
  davinci: ^2.1.1
  http: ^1.0.0
  args: ^2.5.0
  intl: ^0.20.2
  widget_and_text_animator: ^1.1.5
  freedesktop_desktop_entry: ^0.6.1
  collection: ^1.19.1
  material_symbols_icons: ^4.2906.0
  fuzzywuzzy: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  jdwm:
    path: vendor/jdwm

analyzer:
  exclude:
    - vendor/**

flutter:

  uses-material-design: true

  assets:
    - resources/images/desktop/backgrounds/
    - resources/images/desktop/backgrounds/.private/
    - resources/images/null.png
    - resources/images/_icontheme/Default/apps/